# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-30 19:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0010_change_on_delete_behaviour'),
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gallerypage',
            old_name='title_left',
            new_name='page_title',
        ),
        migrations.RemoveField(
            model_name='gallerypage',
            name='title_right',
        ),
        migrations.AddField(
            model_name='gallerypage',
            name='main_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
    ]
