# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-26 15:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0003_galleriespage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gallerypage',
            name='main_image',
        ),
        migrations.RemoveField(
            model_name='gallerypage',
            name='page_title',
        ),
    ]
